### ISSUE TITLE
Profile Borges node to discover bottlenecks

### ISSUE THREAD

**Issue by ajnavarro** [src-d/borges#156]
Plan:

 - [x] Profile Borges consumer in local
     - Compare to [previous profiles](https://gist.github.com/bzz/f7adb8abd32502998c3427179742c468#performance-of-data-collection-pipeline)
 - [x] Profile Borges consumer on cluster

**Comment by bzz** [comment]
After local profiling, there are 2 main slow points:

 - traversing all commits to pick a RootCommit for each reference, after a clone
![borges-local-pprof002-5min](https://user-images.githubusercontent.com/5582506/29977635-59faf5cc-8f3e-11e7-841b-345c1b848b83.png)


 - pushing reference to the `.tmp` siva file in local FS
![borges-profile-push](https://user-images.githubusercontent.com/5582506/29977220-ee54e8d8-8f3c-11e7-9e44-9314c19de36e.gif)

**Comment by erizocosmico** [comment]
Fix for the first bottleneck: https://github.com/src-d/borges/pull/157

**Comment by erizocosmico** [comment]
Fix for the i/o bottleneck: https://github.com/src-d/go-git/pull/575

**Comment by bzz** [comment]
For remote profiling, 2 next k8s descriptors were used:

```
kubectl create -f borges-consumer-profiler-service.yml
kubectl apply -f borges-consumer.yaml
kubectl describe svc borges-consumer-profiler
```

<details>

**borges-consumer-profiler-service.yml**

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: borges-consumer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: borges-consumer
    spec:
      nodeSelector:
        srcd.host/type: worker
      containers:
      - name: borges
        image: quay.io/srcd/borges:v0.6.3
        ports:
          - containerPort: 6061
        command: ['borges','consumer','--workers=12','--loglevel=debug', '--timeout=2h', '--profiler' ]
        env:
        - name: CONFIG_BROKER
          value: 'amqp://guest:guest@rabbitmq:5672'
        - name: CONFIG_DBUSER
          value: testing
        - name: CONFIG_DBPASS
          value: testing
        - name: CONFIG_DBHOST
          value: postgres
        - name: CONFIG_DBNAME
          value: testing
        - name: CONFIG_TEMP_DIR
          value: /borges/tmp
        - name: CONFIG_ROOT_REPOSITORIES_DIR
          value: /borges/root-repositories
        - name: CONFIG_LOCKING
          value: 'etcd:http://etcd:2379'
        - name: HADOOP_USER_NAME
          value: root
        - name: CONFIG_HDFS
          value: 'hdfs-namenode:8020'
      imagePullSecrets:
      - name: quay
```

**borges-consumer-profiler-service.yml**

```
apiVersion: v1
kind: Service
metadata:
  name: borges-consumer-profiler
  labels:
    app: borges-consumer
spec:
  type: ClusterIP
  ports:
    - port: 6061
      targetPort: 6061
      protocol: TCP
      name: borges-consumer-profiler
  selector:
    app: borges-consumer
```

</ details>


**60s profile from the staging Cluster**

![cluster-profile001-60s](https://user-images.githubusercontent.com/5582506/30023122-8904f976-916e-11e7-81db-5faae8306c05.png)
